import { ArrowRight, BookOpen, FileText, MessageCircleQuestion, Users } from "lucide-react";
import Link from "next/link";
import type { OpportunityCommunityHub } from "@/types/opportunity-knowledge-hub";

function Block({ icon: Icon, title, children }: { icon: typeof Users; title: string; children: React.ReactNode }) {
  return <section className="rounded-[18px] border border-[#dce4e0] bg-white p-4"><div className="mb-3 flex items-center gap-2"><span className="grid size-8 place-items-center rounded-[11px] bg-[#eaf7f2] text-[#078166]"><Icon size={14} /></span><h3 className="text-[11px] font-semibold text-[#29493c]">{title}</h3></div>{children}</section>;
}

export function OpportunityCommunityPreview({ hub }: { hub: OpportunityCommunityHub }) {
  const hubHref = `/comunidade/${hub.opportunitySlug}`;
  return <div><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><p className="max-w-xl text-[10px] leading-5 text-[#69756f]">Experiências, dúvidas e conhecimento compartilhado ao redor desta oportunidade.</p>{hub.activeNow > 10 && <span className="inline-flex items-center gap-2 rounded-full bg-[#eaf7f1] px-3 py-1.5 text-[8px] font-semibold text-[#078166]"><Users size={11} />{hub.activeNow} estudantes nesta comunidade</span>}</div><div className="grid gap-3 sm:grid-cols-2">
    <Block icon={MessageCircleQuestion} title="Perguntas"><div className="divide-y divide-[#e8ecea]">{hub.questions.slice(0, 2).map((question) => <Link href={`${hubHref}?tab=questions#${question.id}`} className="block py-3 first:pt-0 last:pb-0 no-underline" key={question.id}><strong className="block text-[10px] leading-4 text-[#365247]">{question.title}</strong><span className="mt-1 block text-[8px] text-[#89938e]">{question.replies} respostas · {question.lastActivity}</span></Link>)}</div></Block>
    <Block icon={BookOpen} title="Experiências"><div className="divide-y divide-[#e8ecea]">{hub.experiences.slice(0, 2).map((experience) => <Link href={`${hubHref}?tab=experiences#${experience.id}`} className="block py-3 first:pt-0 last:pb-0 no-underline" key={experience.id}><strong className="block text-[10px] leading-4 text-[#365247]">{experience.title}</strong><span className="mt-1 block text-[8px] text-[#89938e]">{experience.author} · {experience.readTime}</span></Link>)}</div></Block>
    <Block icon={FileText} title="Recursos compartilhados"><div className="divide-y divide-[#e8ecea]">{hub.sharedResources.slice(0, 2).map((resource) => <Link href={`${hubHref}?tab=resources#${resource.id}`} className="block py-3 first:pt-0 last:pb-0 no-underline" key={resource.id}><strong className="block text-[10px] leading-4 text-[#365247]">{resource.title}</strong><span className="mt-1 block text-[8px] text-[#89938e]">{resource.site} · {resource.saves} pessoas salvaram</span></Link>)}</div></Block>
    <Block icon={Users} title="Pessoas"><div className="py-1"><strong className="block text-[10px] leading-4 text-[#365247]">Participantes, aprovados e mentores</strong><span className="mt-1 block text-[8px] leading-4 text-[#89938e]">Encontre quem pode compartilhar contexto sobre esta experiência.</span><Link href={`${hubHref}?tab=people`} className="mt-3 inline-flex items-center gap-1 text-[8px] font-semibold text-[#078166] no-underline">Conhecer pessoas <ArrowRight size={10} /></Link></div></Block>
  </div><Link href={hubHref} className="mt-4 flex min-h-12 items-center justify-between rounded-[16px] border border-[#bcd9cd] bg-[#edf8f3] px-5 text-[10px] font-semibold text-[#08745d] no-underline transition hover:border-[#079272]/40 hover:bg-[#e4f5ed]">Ver tudo o que está acontecendo nesta oportunidade <ArrowRight size={14} /></Link></div>;
}
