"use client";

import { AnimatePresence, motion } from "framer-motion";
import { Activity as ActivityIcon, ArrowRight, BellRing, BookOpen, Bookmark, CalendarClock, Check, CheckCircle2, ChevronRight, Clock3, Compass, FileCheck2, HelpCircle, History, ListChecks, MessageCircle, Newspaper, Play, Route, Sparkles, Target, UserRound, Users } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { loadJourneyProfileExtension, ProfileUnlocks } from "@/components/journey/profile-unlocks";
import { useAuthentication } from "@/components/auth/authentication-provider";
import { OpportunityWorkspaceNav } from "@/components/opportunity-workspace-nav";
import { useOpportunityJourney } from "@/components/opportunity-journey-provider";
import { SiteHeader } from "@/components/site-header";
import { useJourneyOnboarding } from "@/hooks/use-journey-onboarding";
import { createJourneyPlan } from "@/services/journey-planner-service";
import type { JourneyGlobalProgress, JourneyMission, JourneyPriority, JourneyUpdate } from "@/types/journey-plan";
import type { JourneyStage } from "@/types/opportunity-journey";
import type { JourneyProfileExtension } from "@/types/journey-profile";

const reveal = { initial: { opacity: 0, y: 10 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: "-30px" }, transition: { duration: .28, ease: "easeOut" as const } };

function SectionTitle({ eyebrow, title, description, aside }: { eyebrow: string; title: string; description?: string; aside?: React.ReactNode }) {
  return <header className="mb-5 flex items-end justify-between gap-5"><div><span className="text-[10px] font-bold uppercase tracking-[.15em] text-[#078166]">{eyebrow}</span><h2 className="mt-1.5 text-[clamp(1.55rem,2.6vw,2rem)] font-semibold leading-tight tracking-[-.045em] text-[#17372b]">{title}</h2>{description && <p className="mt-2 text-[12px] leading-5 text-[#6d7973]">{description}</p>}</div>{aside}</header>;
}

function QuickAction({ href, icon: Icon, label, primary = false }: { href: string; icon: typeof Play; label: string; primary?: boolean }) {
  return <Link href={href} className={`group flex min-h-12 items-center gap-3 rounded-[15px] border px-4 text-[11px] font-semibold no-underline transition-all ${primary ? "border-[#079272] bg-[#079272] shadow-[0_10px_25px_rgba(7,146,114,.17)] hover:bg-[#067a60]" : "border-[#d8e1dc] bg-white text-[#365247] hover:border-[#9bc8b9] hover:shadow-sm"}`} style={primary ? { color: "#fff" } : undefined}><Icon size={16} /><span>{label}</span><ChevronRight size={14} className="ml-auto transition-transform group-hover:translate-x-0.5" /></Link>;
}

function DashboardHeader({ pendingCount, firstHref, displayName }: { pendingCount: number; firstHref: string; displayName?: string }) {
  const [greeting, setGreeting] = useState("Olá");
  useEffect(() => {
    const hour = new Date().getHours();
    setGreeting(hour < 12 ? "Bom dia" : hour < 18 ? "Boa tarde" : "Boa noite");
  }, []);
  return <section className="border-b border-[#dae2de] bg-white"><div className="mx-auto grid w-[min(1180px,calc(100%-40px))] gap-6 py-7 lg:grid-cols-[minmax(0,1fr)_620px] lg:items-center"><div><div className="flex items-center gap-2"><span className="text-[10px] font-bold uppercase tracking-[.15em] text-[#078166]">Minha Jornada</span><span className="size-1 rounded-full bg-[#b8c4be]" /><span className="text-[10px] text-[#7b8781]">Atualizada agora</span></div><h1 className="mt-2 text-[clamp(2rem,4vw,3.25rem)] font-semibold tracking-[-.055em] text-[#17372b]">{greeting}{displayName ? `, ${displayName}` : ""}.</h1><p className="mt-1 text-sm text-[#66736d]">{pendingCount > 0 ? <>Você tem <strong className="text-[#17372b]">{pendingCount} {pendingCount === 1 ? "ação pendente" : "ações pendentes"}</strong> para hoje.</> : "Você não tem ações urgentes hoje."}</p></div><nav className="grid gap-2 sm:grid-cols-3" aria-label="Ações principais da Jornada"><QuickAction href={firstHref} icon={Play} label="Continuar candidatura" primary /><QuickAction href="#novidades" icon={BellRing} label="Ver novidades" /><QuickAction href="#comunidade" icon={HelpCircle} label="Pedir ajuda" /></nav></div></section>;
}

function TodayMission({ mission }: { mission: JourneyMission }) {
  return <motion.article layout className="relative overflow-hidden rounded-[26px] bg-[#173b30] p-6 text-white shadow-[0_20px_50px_rgba(19,55,43,.16)] sm:p-8"><div className="absolute -right-8 -top-24 size-72 rounded-full bg-[#32c39a]/14 blur-3xl" /><div className="relative grid gap-7 lg:grid-cols-[minmax(0,1.25fr)_minmax(280px,.75fr)] lg:items-center"><div><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-[14px] bg-white/10 text-[#7ce0c5]"><Target size={18} /></span><div><span className="block text-[9px] font-bold uppercase tracking-[.15em] text-[#7ce0c5]">Missão de hoje</span><span className="mt-0.5 block text-[10px] text-white/48">O avanço mais valioso para fazer agora</span></div></div><h2 className="mt-6 max-w-2xl text-[clamp(1.65rem,3vw,2.35rem)] font-semibold leading-[1.15] tracking-[-.045em] text-white">{mission.title}</h2><p className="mt-2 text-[13px] font-medium text-white/62">{mission.context}</p></div><div className="rounded-[20px] border border-white/10 bg-white/[.06] p-5"><div className="grid grid-cols-[auto_1fr] gap-x-3 gap-y-4"><span className="grid size-8 place-items-center rounded-xl bg-white/8 text-[#7ce0c5]"><LightbulbIcon /></span><div><span className="block text-[8px] font-bold uppercase tracking-[.12em] text-white/42">Por que agora</span><p className="mt-1 text-[10px] leading-5 text-white/72">{mission.why}</p></div><span className="grid size-8 place-items-center rounded-xl bg-white/8 text-[#7ce0c5]"><Clock3 size={14} /></span><div><span className="block text-[8px] font-bold uppercase tracking-[.12em] text-white/42">Tempo estimado</span><p className="mt-1 text-[11px] font-semibold text-white/82">{mission.minutes} minutos</p></div><span className="grid size-8 place-items-center rounded-xl bg-white/8 text-[#7ce0c5]"><Sparkles size={14} /></span><div><span className="block text-[8px] font-bold uppercase tracking-[.12em] text-white/42">Isso desbloqueia</span><p className="mt-1 text-[10px] leading-5 text-white/72">{mission.unlocks}</p></div></div><Link href={mission.href} className="mt-5 flex min-h-11 items-center justify-center gap-2 rounded-full bg-white text-[11px] font-semibold no-underline transition-transform hover:-translate-y-0.5" style={{ color: "#173b30" }}>Começar agora <ArrowRight size={14} /></Link></div></div></motion.article>;
}

function LightbulbIcon() { return <Sparkles size={14} />; }

function GlobalProgress({ progress }: { progress: JourneyGlobalProgress }) {
  const weeklyPercentage = Math.round((progress.weeklyCompleted / progress.weeklyTotal) * 100);
  const stats = [{ label: "Concluídas", value: progress.completedOpportunities }, { label: "Ativas", value: progress.activeOpportunities }, { label: "Dias avançando", value: progress.streakDays }];
  return <section className="mt-4 grid gap-3 rounded-[22px] border border-[#d7e0dc] bg-white p-4 shadow-[0_9px_26px_rgba(28,54,43,.04)] md:grid-cols-[1fr_1.2fr_1.2fr]"><div className="grid grid-cols-3 divide-x divide-[#e4e9e6]">{stats.map((stat) => <div className="px-3 first:pl-1" key={stat.label}><strong className="block text-xl font-semibold tracking-[-.04em] text-[#17372b]">{stat.value}</strong><span className="mt-1 block text-[8px] font-semibold uppercase tracking-[.1em] text-[#89938e]">{stat.label}</span></div>)}</div><div className="border-t border-[#e4e9e6] pt-3 md:border-l md:border-t-0 md:pl-5 md:pt-0"><div className="flex items-center justify-between text-[9px]"><span className="font-semibold text-[#456156]">Progresso da semana</span><span className="text-[#7d8983]">{progress.weeklyCompleted}/{progress.weeklyTotal} etapas</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#e7ece9]"><motion.i className="block h-full rounded-full bg-[#079272]" initial={{ width: 0 }} animate={{ width: `${weeklyPercentage}%` }} transition={{ duration: .65, ease: "easeOut" }} /></div></div><div className="border-t border-[#e4e9e6] pt-3 md:border-l md:border-t-0 md:pl-5 md:pt-0"><span className="text-[8px] font-bold uppercase tracking-[.11em] text-[#89938e]">Marcos recentes</span><div className="mt-2 flex flex-wrap gap-2">{progress.milestones.length > 0 ? progress.milestones.slice(0, 2).map((milestone) => <span className="inline-flex items-center gap-1.5 text-[9px] font-medium text-[#08745d]" key={milestone}><CheckCircle2 size={12} />{milestone}</span>) : <span className="text-[9px] text-[#7d8983]">Seu primeiro marco aparecerá aqui.</span>}</div></div></section>;
}

const updateIcons = { opening: CalendarClock, deadline: BellRing, result: Newspaper, material: BookOpen, community: MessageCircle, mentor: UserRound, person: Users, saved: Bookmark, checklist: FileCheck2 };

function ActivityFeed({ updates }: { updates: JourneyUpdate[] }) {
  return <section id="novidades"><SectionTitle eyebrow="Atividade" title="Atividades da sua Jornada" description="O que mudou e o que você realizou, em ordem cronológica." />{updates.length > 0 ? <div className="grid gap-2.5">{updates.map((update, index) => { const Icon = updateIcons[update.icon]; return <motion.div layout initial={{ opacity: 0, x: -8 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: index * .04 }} className="flex min-h-[76px] items-center gap-4 rounded-[18px] border border-[#d8e1dc] bg-white px-4 py-3 shadow-[0_7px_20px_rgba(28,54,43,.035)] sm:px-5" key={update.id}><span className="grid size-10 shrink-0 place-items-center rounded-[14px] bg-[#eaf7f2] text-[#078166]"><Icon size={16} /></span><div className="min-w-0 flex-1"><p className="text-[11px] font-medium leading-5 text-[#365247]">{update.text}</p><time className="mt-1 block text-[9px] text-[#8a948f]">{update.timestamp}</time></div><Link href={update.href} className="inline-flex shrink-0 items-center gap-1.5 rounded-full border border-[#dce4e0] px-3 py-2 text-[9px] font-semibold text-[#078166] no-underline hover:bg-[#edf7f3]">{update.actionLabel}<ArrowRight size={11} /></Link></motion.div>; })}</div> : <div className="flex min-h-[76px] items-center gap-4 rounded-[18px] border border-[#d8e1dc] bg-white px-5"><span className="grid size-10 place-items-center rounded-[14px] bg-[#eaf7f2] text-[#078166]"><Check size={16} /></span><p className="text-[11px] text-[#607068]">Tudo em dia. As mudanças das oportunidades aparecerão aqui.</p></div>}</section>;
}

const healthStyles = { onTrack: "bg-[#e9f7f1] text-[#08745d]", attention: "bg-[#fff4df] text-[#95661e]", urgent: "bg-[#ffede7] text-[#a84d35]" };
const statusOptions: { value: JourneyStage; label: string }[] = [
  { value: "preparing", label: "Candidatando" },
  { value: "participating", label: "Participando" },
  { value: "waitingForResult", label: "Aguardando resultado" },
  { value: "accepted", label: "Aprovado" },
  { value: "rejected", label: "Não aprovado" },
];

function editableStage(stage: JourneyStage): JourneyStage {
  return statusOptions.some((option) => option.value === stage) ? stage : "preparing";
}

function OpportunityProfileRow({ project, onStatusChange }: { project: JourneyPriority; onStatusChange: (stage: JourneyStage) => void }) {
  const progress = Math.min(100, Math.round((project.progress.completed / project.progress.total) * 100));
  const deadline = project.daysLeft !== undefined ? `${project.daysLeft} dias restantes` : project.opportunity.deadline;
  return <motion.article layout initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, x: 20 }} className="grid gap-5 rounded-[22px] border border-[#d5dfda] bg-white p-5 shadow-[0_10px_28px_rgba(28,54,43,.045)] lg:grid-cols-[minmax(220px,1.1fr)_minmax(190px,.8fr)_minmax(210px,.85fr)_auto] lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[8px] font-bold ${healthStyles[project.health]}`}>{project.healthLabel}</span><span className="text-[8px] font-medium text-[#89938e]">{project.opportunity.organization}</span></div><h3 className="mt-2.5 text-[15px] font-semibold leading-6 tracking-[-.03em] text-[#17372b]">{project.opportunity.title}</h3><p className="mt-1 text-[9px] text-[#7d8983]">{deadline}</p></div><div><label className="text-[8px] font-bold uppercase tracking-[.11em] text-[#89938e]" htmlFor={`status-${project.opportunity.id}`}>Seu status</label><div className="relative mt-2"><select id={`status-${project.opportunity.id}`} value={editableStage(project.relationship.stage)} onChange={(event) => onStatusChange(event.target.value as JourneyStage)} className="h-11 w-full appearance-none rounded-[13px] border border-[#cedbd4] bg-[#f5f8f6] px-3 pr-9 text-[10px] font-semibold text-[#29493c] outline-none transition focus:border-[#079272] focus:ring-2 focus:ring-[#079272]/12">{statusOptions.map((option) => <option value={option.value} key={option.value}>{option.label}</option>)}</select><ChevronRight size={13} className="pointer-events-none absolute right-3 top-3.5 rotate-90 text-[#728079]" /></div></div><div><div className="flex items-center justify-between text-[9px]"><span className="font-medium text-[#52615a]">{project.progress.label}</span><span className="text-[#8a948f]">{project.progress.completed}/{project.progress.total}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#e6ebe8]" role="progressbar" aria-valuemin={0} aria-valuemax={project.progress.total} aria-valuenow={project.progress.completed}><motion.i className="block h-full rounded-full bg-[#079272]" initial={{ width: 0 }} animate={{ width: `${progress}%` }} transition={{ duration: .5 }} /></div><div className="mt-3"><span className="text-[8px] font-bold uppercase tracking-[.1em] text-[#89938e]">Próximo passo</span><p className="mt-1 text-[10px] font-semibold text-[#29493c]">{project.nextAction} <small className="font-normal text-[#84908a]">· {project.actionEstimate ?? "≈ 5 minutos"}</small></p></div></div><Link href={`/explorar/${project.opportunity.id}`} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-full bg-[#079272] px-5 text-[10px] font-semibold no-underline lg:min-w-28" style={{ color: "#fff" }}>Continuar <ArrowRight size={12} /></Link></motion.article>;
}

function AccomplishmentCard({ item, onStatusChange }: { item: JourneyPriority; onStatusChange: (stage: JourneyStage) => void }) {
  const approved = ["accepted", "completed"].includes(item.relationship.stage);
  return <motion.article layout initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, x: -18 }} className={`flex min-h-[88px] flex-col gap-4 rounded-[20px] border px-5 py-4 shadow-[0_8px_22px_rgba(28,54,43,.035)] sm:flex-row sm:items-center ${approved ? "border-[#cce3d9] bg-[#eaf7f1]" : "border-[#e1ded8] bg-[#f5f3ef]"}`}><span className={`grid size-10 shrink-0 place-items-center rounded-[14px] ${approved ? "bg-white text-[#078166]" : "bg-white text-[#7a746c]"}`}>{approved ? <CheckCircle2 size={18} /> : <Compass size={17} />}</span><div className="min-w-0 flex-1"><span className={`text-[8px] font-bold uppercase tracking-[.12em] ${approved ? "text-[#078166]" : "text-[#817a72]"}`}>{approved ? "Aprovado" : "Ciclo encerrado"}</span><h3 className="mt-1 text-[13px] font-semibold text-[#29493c]">{item.opportunity.title}</h3><p className="mt-1 text-[9px] text-[#748079]">Atualizado em {new Date(item.relationship.updatedAt).toLocaleDateString("pt-BR")}</p></div><select value={editableStage(item.relationship.stage)} onChange={(event) => onStatusChange(event.target.value as JourneyStage)} aria-label={`Alterar status de ${item.opportunity.title}`} className="h-10 rounded-[12px] border border-black/10 bg-white px-3 text-[9px] font-semibold text-[#365247] outline-none focus:border-[#079272]">{statusOptions.map((option) => <option value={option.value} key={option.value}>{option.label}</option>)}</select><Link href={`/explorar/${item.opportunity.id}`} className="inline-flex min-h-10 items-center justify-center gap-1.5 rounded-full border border-black/10 bg-white px-4 text-[9px] font-semibold text-[#365247] no-underline">Ver oportunidade <ArrowRight size={11} /></Link></motion.article>;
}

function ChecklistSection({ projects }: { projects: JourneyPriority[] }) {
  return <section><SectionTitle eyebrow="Checklists" title="Etapas em andamento" description="O que falta concluir em cada oportunidade ativa." />{projects.length > 0 ? <div className="grid gap-2.5">{projects.map((project) => <article className="flex min-h-[82px] flex-col gap-4 rounded-[18px] border border-[#d8e1dc] bg-[#eef4f1] px-5 py-4 sm:flex-row sm:items-center" key={project.opportunity.id}><span className="grid size-10 shrink-0 place-items-center rounded-[14px] bg-white text-[#078166]"><FileCheck2 size={17} /></span><div className="min-w-0 flex-1"><span className="text-[8px] font-bold uppercase tracking-[.11em] text-[#78857e]">{project.opportunity.title}</span><h3 className="mt-1 text-[12px] font-semibold text-[#29493c]">{project.nextAction}</h3></div><div className="w-full sm:w-52"><div className="flex justify-between text-[8px] text-[#78857e]"><span>{project.progress.completed}/{project.progress.total} etapas</span><span>{project.actionEstimate ?? "≈ 5 minutos"}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white"><i className="block h-full rounded-full bg-[#079272]" style={{ width: `${Math.round((project.progress.completed / project.progress.total) * 100)}%` }} /></div></div><Link href={`/explorar/${project.opportunity.id}`} className="inline-flex min-h-9 items-center justify-center gap-1 rounded-full bg-white px-4 text-[9px] font-semibold text-[#078166] no-underline">Abrir checklist <ArrowRight size={11} /></Link></article>)}</div> : <p className="rounded-[18px] border border-[#d8e1dc] bg-white px-5 py-4 text-[10px] text-[#69766f]">Nenhum checklist ativo no momento.</p>}</section>;
}

type WorkspaceSection = "trajectory" | "checklists" | "activity" | "history";

const workspaceSections: { id: WorkspaceSection; label: string; description: string; icon: typeof Route }[] = [
  { id: "trajectory", label: "Trajetória", description: "Status das oportunidades", icon: Route },
  { id: "checklists", label: "Checklists", description: "Etapas em andamento", icon: ListChecks },
  { id: "activity", label: "Atividades", description: "Mudanças e comunidade", icon: ActivityIcon },
  { id: "history", label: "Histórico", description: "Conquistas e ciclos encerrados", icon: History },
];

function JourneyWorkspace({ plan, onStatusChange }: { plan: ReturnType<typeof createJourneyPlan>; onStatusChange: (opportunityId: number, stage: JourneyStage) => void }) {
  const [activeSection, setActiveSection] = useState<WorkspaceSection>("trajectory");

  const panels: Record<WorkspaceSection, React.ReactNode> = {
    trajectory: <section><SectionTitle eyebrow="Sua trajetória" title="Seu perfil" description="Atualize onde você está em cada oportunidade. A Jornada reorganiza o restante automaticamente." aside={<Link href="/explorar" className="hidden items-center gap-1 text-[10px] font-semibold text-[#078166] no-underline sm:inline-flex">Adicionar oportunidade <ArrowRight size={12} /></Link>} />{plan.projects.length > 0 ? <motion.div layout className="grid gap-3"><AnimatePresence mode="popLayout">{plan.projects.map((project) => <OpportunityProfileRow project={project} onStatusChange={(stage) => onStatusChange(project.opportunity.id, stage)} key={project.opportunity.id} />)}</AnimatePresence></motion.div> : <div className="flex flex-col items-start justify-between gap-5 rounded-[22px] border border-dashed border-[#bfcfc7] bg-white p-6 sm:flex-row sm:items-center"><div className="flex items-center gap-4"><span className="grid size-10 place-items-center rounded-2xl bg-[#edf7f2] text-[#078166]"><Compass size={18} /></span><div><h3 className="text-sm font-semibold">Nenhuma oportunidade ativa.</h3><p className="mt-1 text-[10px] text-[#748079]">Adicione uma oportunidade ou revise seu histórico.</p></div></div><Link href="/explorar" className="inline-flex min-h-11 items-center gap-2 rounded-full bg-[#079272] px-5 text-[11px] font-semibold no-underline" style={{ color: "#fff" }}>Explorar oportunidades <ArrowRight size={13} /></Link></div>}</section>,
    checklists: <ChecklistSection projects={plan.projects} />,
    activity: <div><ActivityFeed updates={plan.updates} /><div className="mt-8"><CommunityPanel plan={plan} /></div></div>,
    history: <section><SectionTitle eyebrow="Histórico" title="Conquistas" description="Oportunidades que já encerraram seu ciclo ativo — com qualquer resultado." />{plan.accomplishments.length > 0 ? <motion.div layout className="grid gap-2.5"><AnimatePresence mode="popLayout">{plan.accomplishments.map((item) => <AccomplishmentCard item={item} onStatusChange={(stage) => onStatusChange(item.opportunity.id, stage)} key={item.opportunity.id} />)}</AnimatePresence></motion.div> : <div className="flex min-h-[76px] items-center gap-4 rounded-[18px] border border-[#d8e1dc] bg-white px-5"><span className="grid size-10 place-items-center rounded-[14px] bg-[#f1f5f3] text-[#6c7973]"><Target size={16} /></span><p className="text-[10px] text-[#69766f]">Oportunidades aprovadas, recusadas ou concluídas aparecerão aqui.</p></div>}</section>,
  };

  return <section className="mt-10 border-y border-[#d9e2dd] bg-[#edf2ef] py-5 sm:py-8"><div className="mx-auto grid w-[min(1180px,calc(100%-40px))] gap-5 lg:grid-cols-[250px_minmax(0,1fr)] lg:gap-8"><aside className="sticky top-[64px] z-20 -mx-5 overflow-x-auto border-y border-[#d8e1dc] bg-[#f7f9f7]/95 px-5 py-3 backdrop-blur-xl lg:top-[88px] lg:mx-0 lg:self-start lg:overflow-visible lg:rounded-[22px] lg:border lg:bg-white lg:p-3" aria-label="Áreas da sua Jornada"><nav className="flex min-w-max gap-2 lg:grid lg:min-w-0">{workspaceSections.map(({ id, label, description, icon: Icon }) => { const active = activeSection === id; return <button type="button" onClick={() => setActiveSection(id)} aria-controls="journey-workspace-panel" aria-current={active ? "page" : undefined} className={`flex items-center gap-3 rounded-[16px] px-3 py-3 text-left transition-all lg:w-full ${active ? "bg-[#e7f5ef] text-[#06735b] shadow-[inset_0_0_0_1px_rgba(7,146,114,.06)]" : "text-[#68756f] hover:bg-[#f1f5f2] hover:text-[#29493c]"}`} key={id}><span className={`grid size-9 shrink-0 place-items-center rounded-[12px] ${active ? "bg-white text-[#079272] shadow-sm" : "bg-[#eef2f0] text-[#627169]"}`}><Icon size={18} /></span><span><strong className="block text-[11px] font-semibold">{label}</strong><small className="mt-0.5 hidden text-[8px] leading-4 opacity-70 lg:block">{description}</small></span></button>; })}</nav></aside><div id="journey-workspace-panel" className="min-h-[420px] rounded-[24px] border border-[#d8e1dc] bg-[#f9faf9] p-5 shadow-[0_12px_34px_rgba(28,54,43,.045)] sm:p-7"><AnimatePresence mode="wait" initial={false}><motion.div key={activeSection} initial={{ opacity: 0, x: 8 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -6 }} transition={{ duration: .18 }}>{panels[activeSection]}</motion.div></AnimatePresence></div></div></section>;
}

function AnonymousJourneyState({ onWhatsApp, onGoogle }: { onWhatsApp: () => void; onGoogle: () => void }) {
  return <section className="relative overflow-hidden bg-[#f3f7f4] py-16 sm:py-24"><div className="absolute right-[8%] top-8 size-64 rounded-full bg-[#079272]/8 blur-3xl" /><div className="relative mx-auto grid w-[min(920px,calc(100%-40px))] gap-10 rounded-[30px] border border-[#d4e1da] bg-white p-7 shadow-[0_24px_70px_rgba(28,54,43,.09)] md:grid-cols-[1fr_.72fr] md:p-10"><div><span className="grid size-12 place-items-center rounded-[17px] bg-[#e9f7f1] text-[#078166]"><Bookmark size={21} /></span><h1 className="mt-7 text-[clamp(2rem,5vw,3.25rem)] font-semibold leading-[1.02] tracking-[-.06em] text-[#17372b]">Sua jornada ainda não está salva.</h1><p className="mt-5 max-w-xl text-[13px] leading-7 text-[#66736d]">Conecte sua Jornada para acompanhar oportunidades, progresso, lembretes e notificações — e continuar exatamente de onde parou em qualquer dispositivo.</p><div className="mt-6 grid gap-2 text-[10px] text-[#456156] sm:grid-cols-2"><span className="flex items-center gap-2"><CheckCircle2 size={14} className="text-[#078166]" />Seu progresso local será preservado</span><span className="flex items-center gap-2"><CheckCircle2 size={14} className="text-[#078166]" />Seu Coach mantém o contexto</span><span className="flex items-center gap-2"><CheckCircle2 size={14} className="text-[#078166]" />Lembretes antes dos prazos</span><span className="flex items-center gap-2"><CheckCircle2 size={14} className="text-[#078166]" />Continuidade entre dispositivos</span></div></div><div className="flex flex-col justify-center rounded-[22px] border border-[#dbe5e0] bg-[#f7faf8] p-5"><span className="text-[9px] font-bold uppercase tracking-[.13em] text-[#078166]">Salvar e continuar</span><button type="button" onClick={onWhatsApp} className="mt-5 flex min-h-13 items-center gap-3 rounded-[15px] bg-[#079272] px-4 text-[11px] font-semibold shadow-[0_10px_24px_rgba(7,146,114,.16)]" style={{ color: "#fff" }}><span className="grid size-8 place-items-center rounded-xl bg-white/12"><MessageCircle size={17} /></span>Continuar com WhatsApp <ArrowRight size={14} className="ml-auto" /></button><button type="button" onClick={onGoogle} className="mt-2.5 flex min-h-13 items-center gap-3 rounded-[15px] border border-[#d8e0dc] bg-white px-4 text-[11px] font-semibold text-[#365247]"><span className="grid size-8 place-items-center rounded-xl bg-[#f1f4f2] text-sm font-bold text-[#4285f4]">G</span>Continuar com Google <ArrowRight size={14} className="ml-auto" /></button><p className="mt-5 text-center text-[8px] leading-4 text-[#8b9590]">Sem senha. Você poderá conectar os dois métodos depois.</p></div></div></section>;
}

function CommunityPanel({ plan }: { plan: ReturnType<typeof createJourneyPlan> }) {
  return <section id="comunidade" className="rounded-[24px] border border-[#d8e1dc] bg-white p-6 shadow-[0_10px_30px_rgba(28,54,43,.045)]"><SectionTitle eyebrow="Comunidade" title="Pessoas fazendo essa oportunidade" description="Avanços e dúvidas recentes de quem está no mesmo caminho." /><div className="mb-4 flex flex-wrap gap-2"><span className="inline-flex items-center gap-1.5 rounded-full bg-[#eaf7f2] px-3 py-1.5 text-[9px] font-semibold text-[#08745d]"><i className="size-1.5 rounded-full bg-[#18a47f]" />8 estudantes preparando agora</span><span className="inline-flex items-center gap-1.5 rounded-full bg-[#f2f5f3] px-3 py-1.5 text-[9px] font-semibold text-[#607068]">2 aprovados disponíveis</span></div>{plan.communityActivity.length > 0 ? <div className="divide-y divide-[#e7ece9]">{plan.communityActivity.map((activity) => <div className="flex gap-3 py-4 first:pt-0 last:pb-0" key={activity.id}><span className="grid size-9 shrink-0 place-items-center rounded-full bg-[#eaf3ef] text-[9px] font-bold text-[#47665a]">{activity.initials}</span><div className="min-w-0 flex-1"><p className="text-[11px] leading-5 text-[#52615a]"><strong className="text-[#29493c]">{activity.person}</strong> {activity.text}.</p><div className="mt-1.5 flex items-center gap-3"><time className="text-[8px] text-[#929b97]">{activity.timestamp}</time><Link href={`/comunidade?oportunidade=${activity.opportunityId}`} className="text-[9px] font-semibold text-[#078166] no-underline hover:underline">{activity.actionLabel}</Link></div></div></div>)}</div> : <div className="rounded-2xl bg-[#f3f7f4] p-4"><p className="text-[11px] leading-5 text-[#607068]">Quando você acompanhar uma oportunidade, encontrará aqui estudantes e mentores relacionados a ela.</p><Link href="/comunidade" className="mt-3 inline-flex items-center gap-1 text-[10px] font-semibold text-[#078166] no-underline">Conhecer a comunidade <ArrowRight size={12} /></Link></div>}</section>;
}

function MomentumCard({ messages }: { messages: string[] }) {
  return <article className="rounded-[22px] border border-[#cfe2d9] bg-[#edf7f2] p-6"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-white text-[#078166]"><Target size={16} /></span><div><span className="text-[9px] font-bold uppercase tracking-[.13em] text-[#078166]">Seu movimento</span><h2 className="mt-0.5 text-lg font-semibold tracking-[-.035em] text-[#17372b]">Progresso que importa</h2></div></div><div className="mt-5 grid gap-2">{messages.map((message) => <p className="flex items-start gap-2 text-[11px] leading-5 text-[#456156]" key={message}><Check size={14} className="mt-0.5 shrink-0 text-[#078166]" />{message}</p>)}</div></article>;
}

export function JourneyPage() {
  const { ready: authenticationReady, isAuthenticated, openAuthentication } = useAuthentication();
  const { journeys, updateJourneyStage } = useOpportunityJourney();
  const { profile } = useJourneyOnboarding();
  const plan = useMemo(() => createJourneyPlan(journeys, profile), [journeys, profile]);
  const [profileExtension, setProfileExtension] = useState<JourneyProfileExtension>({});
  const [profileExtensionReady, setProfileExtensionReady] = useState(false);

  useEffect(() => {
    setProfileExtension(loadJourneyProfileExtension());
    setProfileExtensionReady(true);
  }, []);

  const firstProject = plan.projects[0];
  const firstHref = firstProject ? `/explorar/${firstProject.opportunity.id}` : "/explorar";

  if (!authenticationReady) return <main className="min-h-screen bg-[#f4f7f5]"><SiteHeader /><OpportunityWorkspaceNav active="journey" /><div className="mx-auto mt-16 h-56 w-[min(920px,calc(100%-40px))] animate-pulse rounded-[28px] bg-[#e7eeea]" /></main>;

  if (!isAuthenticated) return <main className="min-h-screen bg-[#f4f7f5] font-[family-name:var(--font-poppins)]"><SiteHeader /><OpportunityWorkspaceNav active="journey" /><AnonymousJourneyState onWhatsApp={() => openAuthentication("journey", undefined, "whatsapp")} onGoogle={() => openAuthentication("journey", undefined, "google")} /></main>;

  return <main className="min-h-screen bg-[#f4f7f5] font-[family-name:var(--font-poppins)] text-[#17372b]">
    <SiteHeader />
    <OpportunityWorkspaceNav active="journey" />
    {profileExtensionReady && <ProfileUnlocks profile={profile} value={profileExtension} onChange={setProfileExtension} />}
    <DashboardHeader pendingCount={plan.dailyActions.length} firstHref={firstHref} displayName={profileExtension.preferredName || profileExtension.firstName} />

    <div className="mx-auto w-[min(1180px,calc(100%-40px))] py-7 sm:py-9">
      <motion.div {...reveal}><TodayMission mission={plan.mission} /><GlobalProgress progress={plan.globalProgress} /></motion.div>

    </div>

    <JourneyWorkspace plan={plan} onStatusChange={updateJourneyStage} />

    <div className="mx-auto w-[min(1180px,calc(100%-40px))] py-10">
      <motion.section {...reveal}><MomentumCard messages={plan.momentum} /></motion.section>
    </div>

    <footer className="border-t border-[#dce4e0] bg-white py-6 text-center text-[9px] text-[#89938e]">Sua Jornada usa dados locais nesta versão.</footer>
  </main>;
}
